services:
  - type: web
    name: spicy-telegram-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn main:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: TELEGRAM_BOT_TOKEN
      - key: OPENROUTER_API_KEY
        fromSecret: OPENROUTER_API_KEY
      - key: MODEL_LAB_API_KEY
        fromSecret: MODEL_LAB_API_KEY
      - key: NOWPAYMENTS_API_KEY
        fromSecret: NOWPAYMENTS_API_KEY
